<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Tests\EoneoPay\Utils\Stubs\Services\ServiceStub' shared autowired service.

return $this->services['Tests\\EoneoPay\\Utils\\Stubs\\Services\\ServiceStub'] = new \Tests\EoneoPay\Utils\Stubs\Services\ServiceStub(new \EoneoPay\Utils\Arr());
