<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSP7tI3g\ComponentTests_EoneoPay_Utils_Stubs_Vendor_Symfony_Component_KernelStubTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSP7tI3g/ComponentTests_EoneoPay_Utils_Stubs_Vendor_Symfony_Component_KernelStubTestDebugContainer.php') {
    touch(__DIR__.'/ContainerSP7tI3g.legacy');

    return;
}

if (!\class_exists(ComponentTests_EoneoPay_Utils_Stubs_Vendor_Symfony_Component_KernelStubTestDebugContainer::class, false)) {
    \class_alias(\ContainerSP7tI3g\ComponentTests_EoneoPay_Utils_Stubs_Vendor_Symfony_Component_KernelStubTestDebugContainer::class, ComponentTests_EoneoPay_Utils_Stubs_Vendor_Symfony_Component_KernelStubTestDebugContainer::class, false);
}

return new \ContainerSP7tI3g\ComponentTests_EoneoPay_Utils_Stubs_Vendor_Symfony_Component_KernelStubTestDebugContainer([
    'container.build_hash' => 'SP7tI3g',
    'container.build_id' => 'ef1f9377',
    'container.build_time' => 1575593063,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSP7tI3g');
